### ISSUE TITLE
The plugin doesn't work for windows

### ISSUE THREAD

**Issue by matiasgql** [mika314/UELlama#1]
I recompiled the plugin and updated the library with the .lib version for work in windows, but the plugin still not working, I also tried another cmake flags, or another versions of llama.cpp, but I'm still having the following error when I start Unreal: 
![imagen](https://github.com/mika314/UELlama/assets/44686929/e1a40be6-58a1-4d90-bbea-a9c1a31fb4bf)

I have CUDA 9.0, 11.6, 11.8 and 12.2

**Comment by mika314** [comment]
I assume you built libllama.dll by following the steps in the readme.

I think Windows has its own way to find DLLs. And I never can remember how Windows does it. As a test, you can put libllama.dll inside the System32 directory. And if it works, gradually find a better location for the DLL.

**Comment by matiasgql** [comment]
Well I build into a .lib and I use the same PublicAdditionalLibraries but for the lib file, I need to put llama.dll somewhere?

**Comment by matiasgql** [comment]
Sorry I closed by mistake, its my first time using the issue page in github

**Comment by mika314** [comment]
-DBUILD_SHARED_LIBS=ON option builds libllama.dll and you need to put it somewhere. I do not know where, as I mentioned above. You can try to put it in the System32 directory, as I believe Windows always looks for DLLs in this directory.

**Comment by matiasgql** [comment]
I copy the llama.dll inside bin/Release and renamed to "libllama.dll" and I put on System32 but still doesn't working, in build/Releases only have .lib and .exp libraries, and I use -DBUILD_SHARED_LIBS=ON

**Comment by matiasgql** [comment]
I recently tried with visual studio 2022 and I still can't build .dll files, for some reason it compiles .lib and .exp even with the configuration setting in .dll

**Comment by mika314** [comment]
I build lllama as a dynamic library because I do not know how to configure CMake to generate Position Independent Code (PIC) in the static library. I do not know if it is a concern on Windows. So maybe linking statically to the llama.lib is ok.

The error message is extremely vague. Can you look at the log? Maybe it will give you more information.

You can find logs in `Saved/Logs` directory.

**Comment by mika314** [comment]
Also, have you updated this line?

https://github.com/mika314/UELlama/blob/0e03c7993a3c3297e0200f815a8c294633ecfad6/Source/UELlama/UELlama.Build.cs#L61C1-L62C1

**Comment by matiasgql** [comment]
yes, I updated a little bit the code for test if it work, also deleted that "if", the log is extremely vague also, here is the part that includes the UELlama plugin:


> [2023.09.15-18.01.21:843][  0]LogWindows:   Looked in: C:\Program Files\Epic Games\UE_5.3\Engine\Plugins\Online\Android\OnlineSubsystemGooglePlay\Binaries\Win64
> [2023.09.15-18.01.21:843][  0]LogWindows:   Looked in: C:\Users\Usuario\OneDrive\Documentos\Unreal Projects\LlamaCPP_Integration\Plugins\UELlama\Binaries\Win64
> [2023.09.15-18.01.21:843][  0]LogWindows:   Looked in: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\Win64\Android
> [2023.09.15-18.01.21:843][  0]LogWindows:   Looked in: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\Win64\D3D12
> [2023.09.15-18.01.21:843][  0]LogWindows:   Looked in: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\Win64\DML
> [2023.09.15-18.01.21:843][  0]LogWindows:   Looked in: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\Win64\IOS
> [2023.09.15-18.01.21:843][  0]LogWindows:   Looked in: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\Win64\Linux
> [2023.09.15-18.01.21:843][  0]LogWindows:   Looked in: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\Win64\LinuxArm64
> [2023.09.15-18.01.21:843][  0]LogPluginManager: Error: Plugin 'UELlama' failed to load because module 'UELlama' could not be loaded.  There may be an operating system error or the module may not be properly set up.
> [2023.09.15-18.01.25:199][  0]Message dialog closed, result: Ok, title: Message, text: Plugin 'UELlama' failed to load because module 'UELlama' could not be loaded.  There may be an operating system error or the module may not be properly set up.
> [2023.09.15-18.01.25:200][  0]LogCore: Engine exit requested (reason: EngineExit() was called)

**Comment by mika314** [comment]
This line 'LogWindows: Looked in...' shows where it is looking for the .dll. Can you try to put the .dll in one of these directories?

**Comment by mika314** [comment]
Can you hit me on Discord so we can iterate faster? My discord: mika.pi

**Comment by matiasgql** [comment]
Oh I solved it putting the llama.dll (without the rename) inside "Plugins/UELlama/Binaries/Win64" thanks!

**Comment by oivio** [comment]
Hi. I am sorry for refreshing this topic but after recent download I come a cross same error on Windows10.
As seen on picture I have dll files in right folders but sadly result is module could not be loaded.

![image](https://github.com/mika314/UELlama/assets/38628851/70259ffc-511a-43e4-9ea3-1279779c06b8)

**Comment by mika314** [comment]
Can you look at the log? Maybe it will give you more information.

You can find logs in `Saved/Logs` directory.

**Comment by oivio** [comment]
> Can you look at the log? Maybe it will give you more information.
> 
> You can find logs in `Saved/Logs` directory.

Thx @mika314 I did have a look and found sus:

`[2023.10.07-15.59.05:339][  0]LogWindows: Failed to load 'H:/Unreal Projects/UELlama2/Plugins/UELlama/Binaries/Win64/UnrealEditor-UELlama.dll' (GetLastError=126)

[2023.10.07-15.59.05:339][  0]LogWindows:   Missing import: llama.dll`

Just in case here is my clean log:
[UELlama2.log](https://github.com/mika314/UELlama/files/12838191/UELlama2.log)

**Comment by mika314** [comment]
`Missing import: cudart64_12.dll`
Do you have CUDA set up?

**Comment by oivio** [comment]
> `Missing import: cudart64_12.dll` Do you have CUDA set up?

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by oivio** [comment]
![image](https://github.com/mika314/UELlama/assets/38628851/d5211a56-0028-4284-9ff5-186221070fee)

**Comment by mika314** [comment]
Not sure what is missing, maybe you need to set some global environment variables to make the engine find the CUDA DLLs.

@matiasgql, can you help with the setup? According to the logs, the engine cannot find the CUDA DLLs.

```
[2023.10.07-15.59.05:318][  0]LogFileCache: Scanning file cache for directory 'H:/Unreal Projects/UELlama2/Saved/Collections/' took 0.00s
[2023.10.07-15.59.05:319][  0]LogFileCache: Scanning file cache for directory 'H:/Unreal Projects/UELlama2/Content/Developers/Matrix/Collections/' took 0.00s
[2023.10.07-15.59.05:320][  0]LogFileCache: Scanning file cache for directory 'H:/Unreal Projects/UELlama2/Content/Collections/' took 0.00s
[2023.10.07-15.59.05:337][  0]LogWindows: Failed to preload 'H:/Unreal Projects/UELlama2/Plugins/UELlama/Binaries/Win64/llama.dll' (GetLastError=126)
[2023.10.07-15.59.05:337][  0]LogWindows:   Missing import: cudart64_12.dll
[2023.10.07-15.59.05:337][  0]LogWindows:   Missing import: cublas64_12.dll
[2023.10.07-15.59.05:337][  0]LogWindows:   Looked in: ../../../Engine/Binaries/Win64
[2023.10.07-15.59.05:337][  0]LogWindows:   Looked in: H:/Unreal Projects/UELlama2/Binaries/Win64
[2023.10.07-15.59.05:337][  0]LogWindows:   Looked in: H:\Unreal Projects\UELlama2\Binaries\Win64
[2023.10.07-15.59.05:337][  0]LogWindows:   Looked in: C:\Program Files\Epic Games\UE_5.2\Engine\Plugins\Editor\ModelingToolsEditorMode\Binaries\Win64
[2023.10.07-15.59.05:337][  0]LogWindows:   Looked in: C:\Program Files\Epic Games\UE_5.2\Engine\Plugins\Runtime\MeshModelingToolset\Binaries\Win64
```

**Comment by oivio** [comment]
@mika314 your hint `cudart64_12.dll` did let me find solution. 

I did check my CUDA Toolkit and I was on v11.8
So after installing CUDA Toolkit 12.2 Update 2 did solve the issue.

Thank you for your help and an amazing work with this Plugin!

**Comment by matiasgql** [comment]
Yes you will need CUDA 12.2, I was going to update the README soon with the next commit to say that. My wrong, sorry
